#ifndef __META_PREFAB_GRASSLAND__
#define __META_PREFAB_GRASSLAND__

#include "MetaData.hpp"
static MetaPrefab AssetDataGrassLand[] =
{
	{0, 1.0f, { "../Asset/Model/grassland/Axe_Log.obj" }, { {"../Asset/Model/grassland/GrassLands_NEW_C.png","","","../Asset/Model/grassland/GrassLands_NEW_N.png"}}, {}, 0.0f, 0.0f, 0.25f},
	{0, 1.0f, { "../Asset/Model/grassland/Bush_01.obj" }, { {"../Asset/Model/grassland/GrassLands_NEW_C.png","","","../Asset/Model/grassland/GrassLands_NEW_N.png"}}, {}, 0.0f, 0.0f, 0.25f},
	{0, 1.0f, { "../Asset/Model/grassland/Bush_02.obj" }, { {"../Asset/Model/grassland/GrassLands_NEW_C.png","","","../Asset/Model/grassland/GrassLands_NEW_N.png"}}, {}, 0.0f, 0.0f, 0.25f},
	{0, 1.0f, { "../Asset/Model/grassland/Cliff_Face_Dirt_01.obj" }, { {"../Asset/Model/grassland/GrassLands_NEW_C.png","","","../Asset/Model/grassland/GrassLands_NEW_N.png"}}, {}, 0.0f, 0.0f, 0.25f},
	{0, 1.0f, { "../Asset/Model/grassland/Cliff_Face_Dirt_02.obj" }, { {"../Asset/Model/grassland/GrassLands_NEW_C.png","","","../Asset/Model/grassland/GrassLands_NEW_N.png"}}, {}, 0.0f, 0.0f, 0.25f},
	{0, 1.0f, { "../Asset/Model/grassland/Cliff_Face_Dirt_Corner_01.obj" }, { {"../Asset/Model/grassland/GrassLands_NEW_C.png","","","../Asset/Model/grassland/GrassLands_NEW_N.png"}}, {}, 0.0f, 0.0f, 0.25f},
	{0, 1.0f, { "../Asset/Model/grassland/Cliff_Face_Dirt_Corner_02.obj" }, { {"../Asset/Model/grassland/GrassLands_NEW_C.png","","","../Asset/Model/grassland/GrassLands_NEW_N.png"}}, {}, 0.0f, 0.0f, 0.25f},
	{0, 1.0f, { "../Asset/Model/grassland/Cliff_Face_Dirt_Corner_03.obj" }, { {"../Asset/Model/grassland/GrassLands_NEW_C.png","","","../Asset/Model/grassland/GrassLands_NEW_N.png"}}, {}, 0.0f, 0.0f, 0.25f},
	{0, 1.0f, { "../Asset/Model/grassland/Cliff_Face_Dirt_Corner_High_01.obj" }, { {"../Asset/Model/grassland/GrassLands_NEW_C.png","","","../Asset/Model/grassland/GrassLands_NEW_N.png"}}, {}, 0.0f, 0.0f, 0.25f},
	{0, 1.0f, { "../Asset/Model/grassland/Cliff_Face_Dirt_Corner_High_02.obj" }, { {"../Asset/Model/grassland/GrassLands_NEW_C.png","","","../Asset/Model/grassland/GrassLands_NEW_N.png"}}, {}, 0.0f, 0.0f, 0.25f},
	{0, 1.0f, { "../Asset/Model/grassland/Cliff_Face_Dirt_Corner_High_03.obj" }, { {"../Asset/Model/grassland/GrassLands_NEW_C.png","","","../Asset/Model/grassland/GrassLands_NEW_N.png"}}, {}, 0.0f, 0.0f, 0.25f},
	{0, 1.0f, { "../Asset/Model/grassland/Cliff_Face_Dirt_Corner_Inverted_01.obj" }, { {"../Asset/Model/grassland/GrassLands_NEW_C.png","","","../Asset/Model/grassland/GrassLands_NEW_N.png"}}, {}, 0.0f, 0.0f, 0.25f},
	{0, 1.0f, { "../Asset/Model/grassland/Cliff_Face_Dirt_Corner_Inverted_High_01.obj" }, { {"../Asset/Model/grassland/GrassLands_NEW_C.png","","","../Asset/Model/grassland/GrassLands_NEW_N.png"}}, {}, 0.0f, 0.0f, 0.25f},
	{0, 1.0f, { "../Asset/Model/grassland/Cliff_Face_Dirt_High_01.obj" }, { {"../Asset/Model/grassland/GrassLands_NEW_C.png","","","../Asset/Model/grassland/GrassLands_NEW_N.png"}}, {}, 0.0f, 0.0f, 0.25f},
	{0, 1.0f, { "../Asset/Model/grassland/Cliff_Face_Dirt_High_02.obj" }, { {"../Asset/Model/grassland/GrassLands_NEW_C.png","","","../Asset/Model/grassland/GrassLands_NEW_N.png"}}, {}, 0.0f, 0.0f, 0.25f},
	{0, 1.0f, { "../Asset/Model/grassland/Cliff_Face_Grass_01.obj" }, { {"../Asset/Model/grassland/GrassLands_NEW_C.png","","","../Asset/Model/grassland/GrassLands_NEW_N.png"}}, {}, 0.0f, 0.0f, 0.25f},
	{0, 1.0f, { "../Asset/Model/grassland/Cliff_Face_Grass_02.obj" }, { {"../Asset/Model/grassland/GrassLands_NEW_C.png","","","../Asset/Model/grassland/GrassLands_NEW_N.png"}}, {}, 0.0f, 0.0f, 0.25f},
	{0, 1.0f, { "../Asset/Model/grassland/Cliff_Face_Grass_Corner_01.obj" }, { {"../Asset/Model/grassland/GrassLands_NEW_C.png","","","../Asset/Model/grassland/GrassLands_NEW_N.png"}}, {}, 0.0f, 0.0f, 0.25f},
	{0, 1.0f, { "../Asset/Model/grassland/Cliff_Face_Grass_Corner_02.obj" }, { {"../Asset/Model/grassland/GrassLands_NEW_C.png","","","../Asset/Model/grassland/GrassLands_NEW_N.png"}}, {}, 0.0f, 0.0f, 0.25f},
	{0, 1.0f, { "../Asset/Model/grassland/Cliff_Face_Grass_Corner_03.obj" }, { {"../Asset/Model/grassland/GrassLands_NEW_C.png","","","../Asset/Model/grassland/GrassLands_NEW_N.png"}}, {}, 0.0f, 0.0f, 0.25f},
	{0, 1.0f, { "../Asset/Model/grassland/Cliff_Face_Grass_Corner_High_01.obj" }, { {"../Asset/Model/grassland/GrassLands_NEW_C.png","","","../Asset/Model/grassland/GrassLands_NEW_N.png"}}, {}, 0.0f, 0.0f, 0.25f},
	{0, 1.0f, { "../Asset/Model/grassland/Cliff_Face_Grass_Corner_High_02.obj" }, { {"../Asset/Model/grassland/GrassLands_NEW_C.png","","","../Asset/Model/grassland/GrassLands_NEW_N.png"}}, {}, 0.0f, 0.0f, 0.25f},
	{0, 1.0f, { "../Asset/Model/grassland/Cliff_Face_Grass_Corner_High_03.obj" }, { {"../Asset/Model/grassland/GrassLands_NEW_C.png","","","../Asset/Model/grassland/GrassLands_NEW_N.png"}}, {}, 0.0f, 0.0f, 0.25f},
	{0, 1.0f, { "../Asset/Model/grassland/Cliff_Face_Grass_Corner_Inverted_01.obj" }, { {"../Asset/Model/grassland/GrassLands_NEW_C.png","","","../Asset/Model/grassland/GrassLands_NEW_N.png"}}, {}, 0.0f, 0.0f, 0.25f},
	{0, 1.0f, { "../Asset/Model/grassland/Cliff_Face_Grass_Corner_Inverted_02.obj" }, { {"../Asset/Model/grassland/GrassLands_NEW_C.png","","","../Asset/Model/grassland/GrassLands_NEW_N.png"}}, {}, 0.0f, 0.0f, 0.25f},
	{0, 1.0f, { "../Asset/Model/grassland/Cliff_Face_Grass_Corner_Inverted_High_01.obj" }, { {"../Asset/Model/grassland/GrassLands_NEW_C.png","","","../Asset/Model/grassland/GrassLands_NEW_N.png"}}, {}, 0.0f, 0.0f, 0.25f},
	{0, 1.0f, { "../Asset/Model/grassland/Cliff_Face_Grass_Corner_Inverted_High_02.obj" }, { {"../Asset/Model/grassland/GrassLands_NEW_C.png","","","../Asset/Model/grassland/GrassLands_NEW_N.png"}}, {}, 0.0f, 0.0f, 0.25f},
	{0, 1.0f, { "../Asset/Model/grassland/Cliff_Face_Grass_High_01.obj" }, { {"../Asset/Model/grassland/GrassLands_NEW_C.png","","","../Asset/Model/grassland/GrassLands_NEW_N.png"}}, {}, 0.0f, 0.0f, 0.25f},
	{0, 1.0f, { "../Asset/Model/grassland/Cliff_Face_Grass_High_02.obj" }, { {"../Asset/Model/grassland/GrassLands_NEW_C.png","","","../Asset/Model/grassland/GrassLands_NEW_N.png"}}, {}, 0.0f, 0.0f, 0.25f},
	{0, 1.0f, { "../Asset/Model/grassland/Dead_Tree_01.obj" }, { {"../Asset/Model/grassland/GrassLands_NEW_C.png","","","../Asset/Model/grassland/GrassLands_NEW_N.png"}}, {}, 0.0f, 0.0f, 0.25f},
	{0, 1.0f, { "../Asset/Model/grassland/Dead_Tree_02.obj" }, { {"../Asset/Model/grassland/GrassLands_NEW_C.png","","","../Asset/Model/grassland/GrassLands_NEW_N.png"}}, {}, 0.0f, 0.0f, 0.25f},
	{0, 1.0f, { "../Asset/Model/grassland/Dirt_Tile_01.obj" }, { {"../Asset/Model/grassland/GrassLands_NEW_C.png","","","../Asset/Model/grassland/GrassLands_NEW_N.png"}}, {}, 0.0f, 0.0f, 0.25f},
	{0, 1.0f, { "../Asset/Model/grassland/Fallen_log_01.obj" }, { {"../Asset/Model/grassland/GrassLands_NEW_C.png","","","../Asset/Model/grassland/GrassLands_NEW_N.png"}}, {}, 0.0f, 0.0f, 0.25f},
	{0, 1.0f, { "../Asset/Model/grassland/Fallen_log_02.obj" }, { {"../Asset/Model/grassland/GrassLands_NEW_C.png","","","../Asset/Model/grassland/GrassLands_NEW_N.png"}}, {}, 0.0f, 0.0f, 0.25f},
	{0, 1.0f, { "../Asset/Model/grassland/Fence_01.obj" }, { {"../Asset/Model/grassland/GrassLands_NEW_C.png","","","../Asset/Model/grassland/GrassLands_NEW_N.png"}}, {}, 0.0f, 0.0f, 0.25f},
	{0, 1.0f, { "../Asset/Model/grassland/Fence_02.obj" }, { {"../Asset/Model/grassland/GrassLands_NEW_C.png","","","../Asset/Model/grassland/GrassLands_NEW_N.png"}}, {}, 0.0f, 0.0f, 0.25f},
	{0, 1.0f, { "../Asset/Model/grassland/Fence_03.obj" }, { {"../Asset/Model/grassland/GrassLands_NEW_C.png","","","../Asset/Model/grassland/GrassLands_NEW_N.png"}}, {}, 0.0f, 0.0f, 0.25f},
	{0, 1.0f, { "../Asset/Model/grassland/Fence_04.obj" }, { {"../Asset/Model/grassland/GrassLands_NEW_C.png","","","../Asset/Model/grassland/GrassLands_NEW_N.png"}}, {}, 0.0f, 0.0f, 0.25f},
	{0, 1.0f, { "../Asset/Model/grassland/Fence_End_01.obj" }, { {"../Asset/Model/grassland/GrassLands_NEW_C.png","","","../Asset/Model/grassland/GrassLands_NEW_N.png"}}, {}, 0.0f, 0.0f, 0.25f},
	{0, 1.0f, { "../Asset/Model/grassland/Fence_End_02.obj" }, { {"../Asset/Model/grassland/GrassLands_NEW_C.png","","","../Asset/Model/grassland/GrassLands_NEW_N.png"}}, {}, 0.0f, 0.0f, 0.25f},
	{0, 1.0f, { "../Asset/Model/grassland/Fence_End_03.obj" }, { {"../Asset/Model/grassland/GrassLands_NEW_C.png","","","../Asset/Model/grassland/GrassLands_NEW_N.png"}}, {}, 0.0f, 0.0f, 0.25f},
	{0, 1.0f, { "../Asset/Model/grassland/Flowers_01.obj" }, { {"../Asset/Model/grassland/GrassLands_NEW_C.png","","","../Asset/Model/grassland/GrassLands_NEW_N.png"}}, {}, 0.0f, 0.0f, 0.25f},
	{0, 1.0f, { "../Asset/Model/grassland/Flowers_02.obj" }, { {"../Asset/Model/grassland/GrassLands_NEW_C.png","","","../Asset/Model/grassland/GrassLands_NEW_N.png"}}, {}, 0.0f, 0.0f, 0.25f},
	{0, 1.0f, { "../Asset/Model/grassland/Grass_01.obj" }, { {"../Asset/Model/grassland/GrassLands_NEW_C.png","","","../Asset/Model/grassland/GrassLands_NEW_N.png"}}, {}, 0.0f, 0.0f, 0.25f},
	{0, 1.0f, { "../Asset/Model/grassland/Grass_02.obj" }, { {"../Asset/Model/grassland/GrassLands_NEW_C.png","","","../Asset/Model/grassland/GrassLands_NEW_N.png"}}, {}, 0.0f, 0.0f, 0.25f},
	{0, 1.0f, { "../Asset/Model/grassland/Grass_03.obj" }, { {"../Asset/Model/grassland/GrassLands_NEW_C.png","","","../Asset/Model/grassland/GrassLands_NEW_N.png"}}, {}, 0.0f, 0.0f, 0.25f},
	{0, 1.0f, { "../Asset/Model/grassland/Grass_04.obj" }, { {"../Asset/Model/grassland/GrassLands_NEW_C.png","","","../Asset/Model/grassland/GrassLands_NEW_N.png"}}, {}, 0.0f, 0.0f, 0.25f},
	{0, 1.0f, { "../Asset/Model/grassland/Grass_05.obj" }, { {"../Asset/Model/grassland/GrassLands_NEW_C.png","","","../Asset/Model/grassland/GrassLands_NEW_N.png"}}, {}, 0.0f, 0.0f, 0.25f},
	{0, 1.0f, { "../Asset/Model/grassland/Grass_Dirt_Tile_01.obj" }, { {"../Asset/Model/grassland/GrassLands_NEW_C.png","","","../Asset/Model/grassland/GrassLands_NEW_N.png"}}, {}, 0.0f, 0.0f, 0.25f},
	{0, 1.0f, { "../Asset/Model/grassland/Grass_Dirt_Tile_02.obj" }, { {"../Asset/Model/grassland/GrassLands_NEW_C.png","","","../Asset/Model/grassland/GrassLands_NEW_N.png"}}, {}, 0.0f, 0.0f, 0.25f},
	{0, 1.0f, { "../Asset/Model/grassland/Grass_Dirt_Tile_03.obj" }, { {"../Asset/Model/grassland/GrassLands_NEW_C.png","","","../Asset/Model/grassland/GrassLands_NEW_N.png"}}, {}, 0.0f, 0.0f, 0.25f},
	{0, 1.0f, { "../Asset/Model/grassland/Grass_Dirt_Tile_04.obj" }, { {"../Asset/Model/grassland/GrassLands_NEW_C.png","","","../Asset/Model/grassland/GrassLands_NEW_N.png"}}, {}, 0.0f, 0.0f, 0.25f},
	{0, 1.0f, { "../Asset/Model/grassland/Grass_Dirt_Tile_05.obj" }, { {"../Asset/Model/grassland/GrassLands_NEW_C.png","","","../Asset/Model/grassland/GrassLands_NEW_N.png"}}, {}, 0.0f, 0.0f, 0.25f},
	{0, 1.0f, { "../Asset/Model/grassland/Grass_Dirt_Tile_06.obj" }, { {"../Asset/Model/grassland/GrassLands_NEW_C.png","","","../Asset/Model/grassland/GrassLands_NEW_N.png"}}, {}, 0.0f, 0.0f, 0.25f},
	{0, 1.0f, { "../Asset/Model/grassland/Grass_Dirt_Tile_07.obj" }, { {"../Asset/Model/grassland/GrassLands_NEW_C.png","","","../Asset/Model/grassland/GrassLands_NEW_N.png"}}, {}, 0.0f, 0.0f, 0.25f},
	{0, 1.0f, { "../Asset/Model/grassland/Grass_Dirt_Tile_08.obj" }, { {"../Asset/Model/grassland/GrassLands_NEW_C.png","","","../Asset/Model/grassland/GrassLands_NEW_N.png"}}, {}, 0.0f, 0.0f, 0.25f},
	{0, 1.0f, { "../Asset/Model/grassland/Grass_Dirt_Tile_09.obj" }, { {"../Asset/Model/grassland/GrassLands_NEW_C.png","","","../Asset/Model/grassland/GrassLands_NEW_N.png"}}, {}, 0.0f, 0.0f, 0.25f},
	{0, 1.0f, { "../Asset/Model/grassland/Grass_Dirt_Tile_10.obj" }, { {"../Asset/Model/grassland/GrassLands_NEW_C.png","","","../Asset/Model/grassland/GrassLands_NEW_N.png"}}, {}, 0.0f, 0.0f, 0.25f},
	{0, 1.0f, { "../Asset/Model/grassland/Grass_Dirt_Tile_11.obj" }, { {"../Asset/Model/grassland/GrassLands_NEW_C.png","","","../Asset/Model/grassland/GrassLands_NEW_N.png"}}, {}, 0.0f, 0.0f, 0.25f},
	{0, 1.0f, { "../Asset/Model/grassland/Grass_Dirt_Tile_12.obj" }, { {"../Asset/Model/grassland/GrassLands_NEW_C.png","","","../Asset/Model/grassland/GrassLands_NEW_N.png"}}, {}, 0.0f, 0.0f, 0.25f},
	{0, 1.0f, { "../Asset/Model/grassland/Grass_Tile_01.obj" }, { {"../Asset/Model/grassland/GrassLands_NEW_C.png","","","../Asset/Model/grassland/GrassLands_NEW_N.png"}}, {}, 0.0f, 0.0f, 0.25f},
	{0, 1.0f, { "../Asset/Model/grassland/Grasslands_Landmass_01.obj" }, { {"../Asset/Model/grassland/GrassLands_NEW_C.png","","","../Asset/Model/grassland/GrassLands_NEW_N.png"}}, {}, 0.0f, 0.0f, 0.25f},
	{0, 1.0f, { "../Asset/Model/grassland/Grasslands_Landmass_02.obj" }, { {"../Asset/Model/grassland/GrassLands_NEW_C.png","","","../Asset/Model/grassland/GrassLands_NEW_N.png"}}, {}, 0.0f, 0.0f, 0.25f},
	{0, 1.0f, { "../Asset/Model/grassland/Grasslands_Landmass_03.obj" }, { {"../Asset/Model/grassland/GrassLands_NEW_C.png","","","../Asset/Model/grassland/GrassLands_NEW_N.png"}}, {}, 0.0f, 0.0f, 0.25f},
	{0, 1.0f, { "../Asset/Model/grassland/Grasslands_Landmass_04.obj" }, { {"../Asset/Model/grassland/GrassLands_NEW_C.png","","","../Asset/Model/grassland/GrassLands_NEW_N.png"}}, {}, 0.0f, 0.0f, 0.25f},
	{0, 1.0f, { "../Asset/Model/grassland/Grasslands_Landmass_05.obj" }, { {"../Asset/Model/grassland/GrassLands_NEW_C.png","","","../Asset/Model/grassland/GrassLands_NEW_N.png"}}, {}, 0.0f, 0.0f, 0.25f},
	{0, 1.0f, { "../Asset/Model/grassland/Grasslands_Landmass_06.obj" }, { {"../Asset/Model/grassland/GrassLands_NEW_C.png","","","../Asset/Model/grassland/GrassLands_NEW_N.png"}}, {}, 0.0f, 0.0f, 0.25f},
	{0, 1.0f, { "../Asset/Model/grassland/Grasslands_Landmass_07.obj" }, { {"../Asset/Model/grassland/GrassLands_NEW_C.png","","","../Asset/Model/grassland/GrassLands_NEW_N.png"}}, {}, 0.0f, 0.0f, 0.25f},
	{0, 1.0f, { "../Asset/Model/grassland/Lamp_Post.obj" }, { {"../Asset/Model/grassland/GrassLands_NEW_C.png","","","../Asset/Model/grassland/GrassLands_NEW_N.png"}}, {}, 0.0f, 0.0f, 0.25f},
	{0, 1.0f, { "../Asset/Model/grassland/Lrg_Tree.obj" }, { {"../Asset/Model/grassland/GrassLands_NEW_C.png","","","../Asset/Model/grassland/GrassLands_NEW_N.png"}}, {}, 0.0f, 0.0f, 0.25f},
	{0, 1.0f, { "../Asset/Model/grassland/Mountain_Tile_01.obj" }, { {"../Asset/Model/grassland/GrassLands_NEW_C.png","","","../Asset/Model/grassland/GrassLands_NEW_N.png"}}, {}, 0.0f, 0.0f, 0.25f},
	{0, 1.0f, { "../Asset/Model/grassland/Mountain_Tile_02.obj" }, { {"../Asset/Model/grassland/GrassLands_NEW_C.png","","","../Asset/Model/grassland/GrassLands_NEW_N.png"}}, {}, 0.0f, 0.0f, 0.25f},
	{0, 1.0f, { "../Asset/Model/grassland/Pine_Tree.obj" }, { {"../Asset/Model/grassland/GrassLands_NEW_C.png","","","../Asset/Model/grassland/GrassLands_NEW_N.png"}}, {}, 0.0f, 0.0f, 0.25f},
	{0, 1.0f, { "../Asset/Model/grassland/Rubble_01.obj" }, { {"../Asset/Model/grassland/GrassLands_NEW_C.png","","","../Asset/Model/grassland/GrassLands_NEW_N.png"}}, {}, 0.0f, 0.0f, 0.25f},
	{0, 1.0f, { "../Asset/Model/grassland/Rubble_02_End.obj" }, { {"../Asset/Model/grassland/GrassLands_NEW_C.png","","","../Asset/Model/grassland/GrassLands_NEW_N.png"}}, {}, 0.0f, 0.0f, 0.25f},
	{0, 1.0f, { "../Asset/Model/grassland/Rubble_02_Mid.obj" }, { {"../Asset/Model/grassland/GrassLands_NEW_C.png","","","../Asset/Model/grassland/GrassLands_NEW_N.png"}}, {}, 0.0f, 0.0f, 0.25f},
	{0, 1.0f, { "../Asset/Model/grassland/Rubble_03_End.obj" }, { {"../Asset/Model/grassland/GrassLands_NEW_C.png","","","../Asset/Model/grassland/GrassLands_NEW_N.png"}}, {}, 0.0f, 0.0f, 0.25f},
	{0, 1.0f, { "../Asset/Model/grassland/Sign_Post_01.obj" }, { {"../Asset/Model/grassland/GrassLands_NEW_C.png","","","../Asset/Model/grassland/GrassLands_NEW_N.png"}}, {}, 0.0f, 0.0f, 0.25f},
	{0, 1.0f, { "../Asset/Model/grassland/Sign_Post_02.obj" }, { {"../Asset/Model/grassland/GrassLands_NEW_C.png","","","../Asset/Model/grassland/GrassLands_NEW_N.png"}}, {}, 0.0f, 0.0f, 0.25f},
	{0, 1.0f, { "../Asset/Model/grassland/Sign_Post_03.obj" }, { {"../Asset/Model/grassland/GrassLands_NEW_C.png","","","../Asset/Model/grassland/GrassLands_NEW_N.png"}}, {}, 0.0f, 0.0f, 0.25f},
	{0, 1.0f, { "../Asset/Model/grassland/Sign_Post_04.obj" }, { {"../Asset/Model/grassland/GrassLands_NEW_C.png","","","../Asset/Model/grassland/GrassLands_NEW_N.png"}}, {}, 0.0f, 0.0f, 0.25f},
	{0, 1.0f, { "../Asset/Model/grassland/Sign_Post_05.obj" }, { {"../Asset/Model/grassland/GrassLands_NEW_C.png","","","../Asset/Model/grassland/GrassLands_NEW_N.png"}}, {}, 0.0f, 0.0f, 0.25f},
	{0, 1.0f, { "../Asset/Model/grassland/Sign_Post_06.obj" }, { {"../Asset/Model/grassland/GrassLands_NEW_C.png","","","../Asset/Model/grassland/GrassLands_NEW_N.png"}}, {}, 0.0f, 0.0f, 0.25f},
	{0, 1.0f, { "../Asset/Model/grassland/Stone_01.obj" }, { {"../Asset/Model/grassland/GrassLands_NEW_C.png","","","../Asset/Model/grassland/GrassLands_NEW_N.png"}}, {}, 0.0f, 0.0f, 0.25f},
	{0, 1.0f, { "../Asset/Model/grassland/Stone_02.obj" }, { {"../Asset/Model/grassland/GrassLands_NEW_C.png","","","../Asset/Model/grassland/GrassLands_NEW_N.png"}}, {}, 0.0f, 0.0f, 0.25f},
	{0, 1.0f, { "../Asset/Model/grassland/Stone_03.obj" }, { {"../Asset/Model/grassland/GrassLands_NEW_C.png","","","../Asset/Model/grassland/GrassLands_NEW_N.png"}}, {}, 0.0f, 0.0f, 0.25f},
	{0, 1.0f, { "../Asset/Model/grassland/Stone_04.obj" }, { {"../Asset/Model/grassland/GrassLands_NEW_C.png","","","../Asset/Model/grassland/GrassLands_NEW_N.png"}}, {}, 0.0f, 0.0f, 0.25f},
	{0, 1.0f, { "../Asset/Model/grassland/ZGrass_Tile_half_01.obj" }, { {"../Asset/Model/grassland/GrassLands_NEW_C.png","","","../Asset/Model/grassland/GrassLands_NEW_N.png"}}, {}, 0.0f, 0.0f, 0.25f},
	{0, 1.0f, { "../Model/quad.obj" }, { {"../Asset/Model/grassland/shadow.png","","",""}}, {}, 1.0f, 1.0f},
};

static PipelinePrefab PipelineGrassLand[] =
{	
	{{72,41,42,0,1,2,29,30},9},
	{ {88},3},
	{ {1,2,15,17,18,31,34,41,42,48,49,50,51,52,53,54,55,56,57,58,59,60,87},10}
};

#endif //!__META_PREFAB_GRASSLAND__